name: macos_netcore_test_base
inputs:
  collect_tests_from:
    required: false
    default: ".tests.txt"
  locale:
    required: false
    default: en_US.UTF-8
  code_coverage:
    required: false
    default: true
runs:
  using: composite
  steps:
  - uses: "./.github/actions/ulimit"
    with:
      "n": 10240
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-macos-dotnet-sdk-6.0
      path: UPDATE_ME
      restore-keys: v1-macos-dotnet-sdk-6.0
  - name: Export PATH & DOTNET_ROOT
    run: |-
      {
        echo export PATH="$HOME/.dotnet:$PATH"
        echo export DOTNET_ROOT="$HOME/.dotnet"
      } >> $BASH_ENV
    shell: bash
  - name: Install .NET 6.0 SDK
    run: |-
      set -evx
      echo $PATH > /dev/stderr
      if ! command -v dotnet && [[ ! -f "$HOME/.dotnet/dotnet" ]]; then
        curl \
          -L \
          -o /tmp/dotnet-install.sh \
          https://dot.net/v1/dotnet-install.sh
        chmod +x /tmp/dotnet-install.sh
        /tmp/dotnet-install.sh \
          --verbose \
          --channel 6.0
      fi
      command -v dotnet
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/.dotnet/"
      key: v1-macos-dotnet-sdk-6.0
  - uses: "./.github/actions/netcore_test_base"
    with:
      collect_tests_from: "${{ inputs.collect_tests_from }}"
      locale: "${{ inputs.locale }}"
      code_coverage: "${{ inputs.code_coverage }}"
