ignorePatterns:
- dist/
env:
  browser: true
  es2021: true
extends:
- eslint:recommended
- plugin:@typescript-eslint/recommended
- prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
- '@typescript-eslint'
rules:
  max-len: [error, { code: 80 }]
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, double]
  semi: [error, always]
  consistent-return: [error, { treatUndefinedAsUnspecified: true }]
  '@typescript-eslint/consistent-type-exports': error
