using Google.Protobuf;
using Libplanet.Store.Remote.Extensions;
using Libplanet.Store.Remote.Server;
using Libplanet.Store.Trie;

namespace Libplanet.Store.Remote.Client
{
    /// <summary>
    /// The <a href="https://grpc.io/">gRPC</a> client for
    /// <see cref="IKeyValueStore"/>. This class is a thin wrapper around the
    /// <see cref="KeyValueStore.KeyValueStoreClient"/> generated by <c>protoc</c>.
    ///
    /// <para> <see cref="RemoteKeyValueStore"/> needs to be used with the
    /// <see cref="RemoteKeyValueService"/>.
    /// The <see cref="RemoteKeyValueService"/> should be hosted on a remote server or
    /// a local process, and the <see cref="RemoteKeyValueStore"/> should be used on a client.
    /// </para>
    /// </summary>
    public sealed class RemoteKeyValueStore : IKeyValueStore
    {
        private readonly KeyValueStore.KeyValueStoreClient _client;

        /// <summary>
        /// Creates a new instance of <see cref="RemoteKeyValueStore"/>.
        /// </summary>
        /// <param name="client">
        /// The <see cref="KeyValueStore.KeyValueStoreClient"/> to use for communication.
        /// </param>
        public RemoteKeyValueStore(KeyValueStore.KeyValueStoreClient client)
        {
            _client = client;
        }

        /// <inheritdoc/>
        public void Dispose()
        {
            // Do nothing.
        }

        /// <inheritdoc/>
        public byte[] Get(in KeyBytes key)
        {
            GetResponse response = _client.Get(new GetRequest
            {
                Key = key.ToByteString(),
            });

            // _client returns empty list of bytes if the key does not exist.
            // but we want to throw KeyNotFoundException in that case.
            if(response.Exists == false)
            {
                throw new KeyNotFoundException();
            }

            return response.Value.ToByteArray();
        }

        /// <inheritdoc/>
        public void Set(in KeyBytes key, byte[] value) =>
            _client.Set(new SetRequest { Key = key.ToByteString(), Value = ByteString.CopyFrom(value) });

        /// <inheritdoc/>
        public void Set(IDictionary<KeyBytes, byte[]> values)
        {
            var request = new SetMapRequest();
            foreach ((KeyBytes key, byte[] value) in values)
            {
                request.MapField.Add(key.Hex, ByteString.CopyFrom(value));
            }

            _client.SetMap(request);
        }

        /// <inheritdoc/>
        public void Delete(in KeyBytes key) =>
            _client.Delete(new DeleteRequest { Key = key.ToByteString() });

        /// <inheritdoc/>
        public void Delete(IEnumerable<KeyBytes> keys)
        {
            var request = new DeleteCollectionRequest();
            foreach (KeyBytes keyBytes in keys)
            {
                request.Key.Add(keyBytes.ToByteString());
            }

            _client.DeleteCollection(request);
        }

        /// <inheritdoc/>
        public bool Exists(in KeyBytes key) =>
            _client.Exists(new ExistsRequest { Key = key.ToByteString() }).Exists;

        /// <inheritdoc/>
        public IEnumerable<KeyBytes> ListKeys() =>
            _client.ListKeys(new ListKeysRequest()).Keys.Select(KeyBytesExtensions.ToKeyBytes);
    }
}
