#!/bin/bash
set -e

if ! command -v yarn --help > /dev/null; then
  echo warn: yarn is not available\; pre-commit hook is ignored... >&2
  exit 0
fi

if [[ ! -d node_modules ]]; then
  echo warn: installing dependencies... it can take few minutes... >&2
  if [[ "$CI" = "true" ]]; then
    yarn --frozen-lockfile --immutable --immutable-cache --check-cache
  else
    yarn --silent
  fi
fi

yarn dlx eslint "src/**"

# vim: set filetype=sh ts=2 sw=2 et:
