#!/bin/bash
set -e

version_regex='[Rr]elease ([0-9]+\.[0-9]+\.[0-9]+)'
if [[ "$(head -n1 "$1")" =~ $version_regex ]]; then
  version="${BASH_REMATCH[1]}"
  "$(dirname "$0")/validate-release" "$version"
fi

# vim: set filetype=sh ts=2 sw=2 et:
