name: netcore_build_base
inputs:
  collect_tests_to:
    required: false
    default: ".tests.txt"
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - uses: "./.github/actions/concat_files"
    with:
      glob: "*/*.csproj"
      to: ".combined-package-files.txt"
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: v1-deps-{{ arch }}-{{ checksum ".combined-package-files.txt" }}
      path: UPDATE_ME
      restore-keys: |-
        v1-deps-{{ arch }}-{{ checksum ".combined-package-files.txt" }}
        v1-deps-{{ arch }}
  - run: dotnet restore
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.2
    with:
      path: "~/.nuget/packages"
      key: v1-deps-{{ arch }}-{{ checksum ".combined-package-files.txt" }}
  - run: dotnet build --no-restore -c Release -p:SkipSonar=true
    shell: bash
  - name: Collect tests
    run: |-
      set -evx
      if ! command -v dotnet > /dev/null && \
         [[ -d /usr/local/share/dotnet ]]; then
        export PATH="/usr/local/share/dotnet:$PATH"
      fi
      dotnet test --no-restore --no-build -c Release --list-tests \
      > .dotnet-list-tests.txt
      grep '    ' .dotnet-list-tests.txt \
      | sed 's/    /\n    /g' \
      | sed '/^$/d' \
      | grep '^    ' \
      | sed -E 's/^    |\(.*?\)$//g' \
      | uniq \
      | /usr/bin/sort -R --random-source=CHANGES.md \
      > "${{ inputs.collect_tests_to }}"
    shell: bash
  - uses: actions/upload-artifact@v3.1.3
    with:
      path: |-
        ./${{ inputs.collect_tests_to }}
        ./*/bin/
        ./*/obj/